"""Initial migration

Revision ID: 2c9f3837f495
Revises: 
Create Date: 2025-08-29 23:49:42.026859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9f3837f495'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('coordinates', sa.String(length=100), nullable=False),
    sa.Column('temperatures', sa.JSON(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind', sa.JSON(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('haze', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
